# Generated by Django 3.0.3 on 2020-05-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('question', models.TextField(max_length=600)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
